streamline uninstaller with brew uninstall command

diff --git a/scripts/uninstallers/android-studio b/scripts/uninstallers/android-studio
--- a/scripts/uninstallers/android-studio
+++ b/scripts/uninstallers/android-studio
@@ -1,18 +1,34 @@
-rm -Rf /Applications/Android\ Studio.app
-rm -Rf ~/Library/Preferences/AndroidStudio*
-rm -Rf ~/Library/Preferences/Google/AndroidStudio*
-rm -Rf ~/Library/Preferences/com.google.android.*
-rm -Rf ~/Library/Preferences/com.android.*
-rm -Rf ~/Library/Application\ Support/AndroidStudio*
-rm -Rf ~/Library/Application\ Support/Google/AndroidStudio*
-rm -Rf ~/Library/Logs/AndroidStudio*
-rm -Rf ~/Library/Logs/Google/AndroidStudio*
-rm -Rf ~/Library/Caches/AndroidStudio*
-rm -Rf ~/.AndroidStudio*
-rm -Rf ~/.gradle
-rm -Rf ~/AndroidStudioProjects
-rm -Rf ~/Library/Android*
-rm -Rf ~/.emulator_console_auth_token
-rm -Rf ~/Library/Preferences/Google/AndroidStudio*
-rm -Rf ~/Library/Caches/Google/AndroidStudio*
-rm -Rf ~/Library/Logs/Google/AndroidStudio*
+#!/usr/bin/env bash
+set -e
+remove() {
+  entry="$1"
+
+  echo -ne "Removing $entry... "
+  sudo rm -rf "$entry"
+
+  if [[ ! -e "$entry" ]]; then
+    echo -ne "[OK]"
+  else
+    echo -ne "[FAILED]"
+  fi
+  echo
+}
+brew uninstall --cask --quiet android-studio
+remove /Applications/Android\ Studio.app
+remove ~/Library/Preferences/AndroidStudio*
+remove ~/Library/Preferences/Google/AndroidStudio*
+remove ~/Library/Preferences/com.google.android.*
+remove ~/Library/Preferences/com.android.*
+remove ~/Library/Application\ Support/AndroidStudio*
+remove ~/Library/Application\ Support/Google/AndroidStudio*
+remove ~/Library/Logs/AndroidStudio*
+remove ~/Library/Logs/Google/AndroidStudio*
+remove ~/Library/Caches/AndroidStudio*
+remove ~/.AndroidStudio*
+remove ~/.gradle
+remove ~/AndroidStudioProjects
+remove ~/Library/Android*
+remove ~/.emulator_console_auth_token
+remove ~/Library/Preferences/Google/AndroidStudio*
+remove ~/Library/Caches/Google/AndroidStudio*
+remove ~/Library/Logs/Google/AndroidStudio*
diff --git a/scripts/uninstallers/docker-desktop b/scripts/uninstallers/docker-desktop
--- a/scripts/uninstallers/docker-desktop
+++ b/scripts/uninstallers/docker-desktop
@@ -1,28 +1,42 @@
-echo -n 'removing Docker Desktop...'
-sudo rm -Rf /Applications/Docker.app
-sudo rm -f /usr/local/bin/docker
-sudo rm -f /usr/local/bin/docker-machine
-sudo rm -f /usr/local/bin/com.docker.cli
-sudo rm -f /usr/local/bin/docker-compose
-sudo rm -f /usr/local/bin/docker-compose-v1
-sudo rm -f /usr/local/bin/docker-credential-desktop
-sudo rm -f /usr/local/bin/docker-credential-ecr-login
-sudo rm -f /usr/local/bin/docker-credential-osxkeychain
-sudo rm -f /usr/local/bin/hub-tool
-sudo rm -f /usr/local/bin/hyperkit
-sudo rm -f /usr/local/bin/kubectl.docker
-sudo rm -f /usr/local/bin/vpnkit
-sudo rm -Rf ~/.docker
-sudo rm -Rf ~/Library/Containers/com.docker.docker
-sudo rm -Rf ~/Library/Application\ Support/Docker\ Desktop
-sudo rm -Rf ~/Library/Group\ Containers/group.com.docker
-sudo rm -f ~/Library/HTTPStorages/com.docker.docker.binarycookies
-sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
-sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
-sudo rm -Rf ~/Library/Logs/Docker\ Desktop
-sudo rm -Rf /usr/local/lib/docker
-sudo rm -f ~/Library/Preferences/com.docker.docker.plist
-sudo rm -Rf ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
-sudo rm -f ~/Library/Preferences/com.electron.docker-frontend.plist
-brew uninstall --cask docker
-echo ' [done]'
+#!/usr/bin/env bash
+set -e
+remove() {
+  entry="$1"
+
+  echo -ne "Removing $entry... "
+  sudo rm -rf "$entry"
+
+  if [[ ! -e "$entry" ]]; then
+    echo -ne "[OK]"
+  else
+    echo -ne "[FAILED]"
+  fi
+  echo
+}
+
+brew uninstall --zap --quiet --cask docker
+remove /Applications/Docker.app
+remove /usr/local/bin/docker
+remove /usr/local/bin/docker-machine
+remove /usr/local/bin/com.docker.cli
+remove /usr/local/bin/docker-compose
+remove /usr/local/bin/docker-compose-v1
+remove /usr/local/bin/docker-credential-desktop
+remove /usr/local/bin/docker-credential-ecr-login
+remove /usr/local/bin/docker-credential-osxkeychain
+remove /usr/local/bin/hub-tool
+remove /usr/local/bin/hyperkit
+remove /usr/local/bin/kubectl.docker
+remove /usr/local/bin/vpnkit
+remove ~/.docker
+remove ~/Library/Containers/com.docker.docker
+remove ~/Library/Application\ Support/Docker\ Desktop
+remove ~/Library/Group\ Containers/group.com.docker
+remove ~/Library/HTTPStorages/com.docker.docker.binarycookies
+remove /Library/PrivilegedHelperTools/com.docker.vmnetd
+remove /Library/LaunchDaemons/com.docker.vmnetd.plist
+remove ~/Library/Logs/Docker\ Desktop
+remove /usr/local/lib/docker
+remove ~/Library/Preferences/com.docker.docker.plist
+remove ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
+remove ~/Library/Preferences/com.electron.docker-frontend.plist
diff --git a/scripts/uninstallers/edge b/scripts/uninstallers/edge
--- a/scripts/uninstallers/edge
+++ b/scripts/uninstallers/edge
@@ -1,18 +1,35 @@
 #!/usr/bin/env bash
 set -e
-echo -n 'removing Microsoft Edge...'
-rm -fr /Applications/Microsoft\ Edge.app/
-rm -fr ~/Library/Application\ Support/Microsoft/EdgeUpdater/
-rm -fr ~/Library/Application\ Support/CrashReporter/Microsoft*
-rm -fr ~/Library/Preferences/com.microsoft.autoupdate*
-rm -fr ~/Library/Caches/com.microsoft.Edge*
-rm -fr ~/Library/Saved\ Application\ State/com.microsoft.Edge*
-rm -fr ~/Library/Microsoft/EdgeUpdater/
-rm -fr ~/Library/Google/Microsoft\ Edge*
-rm -fr ~/Library/Speech/Speakable\ Items/Application\ Speakable\ Items/Microsoft\ Edge*
-rm -fr ~/Library/LaunchAgents/com.microsoft.Edge*
-rm -fr ~/Library/Preferences/com.google.Keystone.Agent.plist
-rm -fr ~/Library/Caches/com.google.Keystone*
-rm -fr ~/Library/Caches/com.google.SoftwareUpdate
-rm -rf ~/Applications/Edge\ Apps
-echo ' [done]'
+#!/usr/bin/env bash
+set -e
+remove() {
+  entry="$1"
+
+  echo -ne "Removing $entry... "
+  sudo rm -rf "$entry"
+
+  if [[ ! -e "$entry" ]]; then
+    echo -ne "[OK]"
+  else
+    echo -ne "[FAILED]"
+  fi
+  echo
+}
+
+brew uninstall --cask --zap --quiet microsoft-edge
+remove /Applications/Microsoft\ Edge.app/
+remove ~/Library/Caches/Microsoft\ Edge
+remove ~/Library/Preferences/com.microsoft.edge*
+remove ~/Library/Application\ Support/Microsoft/EdgeUpdater/
+remove ~/Library/Application\ Support/CrashReporter/Microsoft*
+remove ~/Library/Preferences/com.microsoft.autoupdate*
+remove ~/Library/Caches/com.microsoft.Edge*
+remove ~/Library/Saved\ Application\ State/com.microsoft.Edge*
+remove ~/Library/Microsoft/EdgeUpdater/
+remove ~/Library/Application\ Support/Microsoft\ Edge*
+remove ~/Library/Speech/Speakable\ Items/Application\ Speakable\ Items/Microsoft\ Edge*
+remove ~/Library/LaunchAgents/com.microsoft.Edge*
+remove ~/Library/Preferences/com.google.Keystone.Agent.plist
+remove ~/Library/Caches/com.google.Keystone*
+remove ~/Library/Caches/com.google.SoftwareUpdate
+remove ~/Applications/Edge\ Apps
diff --git a/scripts/uninstallers/msteams b/scripts/uninstallers/msteams
--- a/scripts/uninstallers/msteams
+++ b/scripts/uninstallers/msteams
@@ -1,7 +1,29 @@
-echo -n 'removing Microsoft Teams... [wip]'
-exit 0;
-rm -fr ~/Library/Caches/com.microsoft.teams
-rm -fr ~/Library/Caches/com.microsoft.teams.shipit
-rm -fr ~/Library/Application\ Support/Microsoft/Teams
-rm -fr ~/Library/Application\ Support/Microsoft/Teams
-echo ' [done]'
+#!/usr/bin/env bash
+set -e
+remove() {
+  entry="$1"
+
+  echo -ne "Removing $entry... "
+  sudo rm -rf "$entry"
+
+  if [[ ! -e "$entry" ]]; then
+    echo -ne "[OK]"
+  else
+    echo -ne "[FAILED]"
+  fi
+  echo
+}
+
+remove ~/Library/Caches/com.microsoft.teams
+remove ~/Library/Caches/com.microsoft.teams.shipit
+remove ~/Library/Application\ Support/Microsoft/Teams
+remove ~/Library/Application\ Support/com.microsoft.teams
+remove ~/Library/Application\ Support/Microsoft/Teams
+remove ~/Library/Application\ Support/Teams
+remove ~/Library/Caches/com.microsoft.teams
+remove ~/Library/Cookies/com.microsoft.teams.binarycookies
+remove ~/Library/Logs/Microsoft\ Teams
+remove ~/Library/Preferences/com.microsoft.teams.plist
+remove ~/Library/Saved\ Application\ State/com.microsoft.teams.savedState
+remove ~/Library/WebKit/com.microsoft.teams
+brew uninstall --cask --zap --quiet microsoft-teams
diff --git a/scripts/uninstallers/vmware-fusion b/scripts/uninstallers/vmware-fusion
--- a/scripts/uninstallers/vmware-fusion
+++ b/scripts/uninstallers/vmware-fusion
@@ -1,18 +1,17 @@
 #!/usr/bin/env bash
-# Usage: ./vmware
-
+set -e
 remove() {
   entry="$1"
 
-  echo -e "Removing $entry ["
+  echo -ne "Removing $entry... "
   sudo rm -rf "$entry"
 
   if [[ ! -e "$entry" ]]; then
-    echo -ne "OK"
+    echo -ne "[OK]"
   else
-    echo -ne "FAILED"
+    echo -ne "[FAILED]"
   fi
-  echo -ne "]"
+  echo
 }
 
 remove "/Applications/VMware Fusion.app"
